### PR TITLE
fixed issue with name/code

### PR DESCRIPTION
**Pull request by perfahlen**
had problems using geojson generated by GeoServer

### CODE REVIEW

**Comment by joeaudette** [comment]
@perfahlen I will accept this pull request, doesn't look like it would break anything. To be honest I ported this to .net core for a project that uses geojson but then did not end up using this on the project because my client already had working code for geojson that met their needs. So I have never actually used this project for anything yet.

**Comment by perfahlen** [comment]
Well, I using it for a project and it fills my needs. Hopefully I see you
March next year.

**Comment by joeaudette** [comment]
Glad it is useful for you. Hope to see you next MVP summit as well, I didn't go this year, is it in March? I thought it was in November

**Comment by perfahlen** [comment]
They changed it, next is March 2018.

**Pull request merged**
